"""empty message

Revision ID: 099c2ecb5bf7
Revises: f234fbaf8de8
Create Date: 2025-11-22 09:52:56.893594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099c2ecb5bf7'
down_revision = 'f234fbaf8de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('mensagem', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
